SPOOL bruno_project_part_9_q1_spool.txt
SELECT TO_CHAR (sysdate, 'Day DD Month Year HH:MI:SS Am') FROM dual;
SET SERVEROUTPUT ON

-- Question 1: des02, script 7clearwater
-- Create a package with OVERLOADING procedure used to insert a new customer. The user has the choice of providing either
-- a/ Last Name, address
-- b/ Last Name, birthdate
-- c/ Last Name, First Name, birthdate
-- d/ Customer id, last name, birthdate
-- In case no customer id is provided, please use a number from a sequence called customer_sequence.

CREATE OR REPLACE PACKAGE CUSTOMER_PACKAGE IS
    PROCEDURE CUSTOMER_INSERT(P_C_LAST VARCHAR2, P_C_ADDRESS VARCHAR2);
    PROCEDURE CUSTOMER_INSERT(P_C_LAST VARCHAR2, P_C_BIRTHDATE DATE);
    PROCEDURE CUSTOMER_INSERT(P_C_LAST VARCHAR2, P_C_FIRST VARCHAR2, P_C_BIRTHDATE DATE);
    PROCEDURE CUSTOMER_INSERT(P_C_ID NUMBER, P_C_LAST VARCHAR2, P_C_BIRTHDATE DATE);
END;
/

DROP SEQUENCE CUSTOMER_SEQUENCE;
CREATE SEQUENCE CUSTOMER_SEQUENCE START WITH 7 NOCACHE;

CREATE OR REPLACE PACKAGE BODY CUSTOMER_PACKAGE IS
    PROCEDURE CUSTOMER_INSERT(P_C_LAST VARCHAR2, P_C_ADDRESS VARCHAR2) AS
    BEGIN
      INSERT INTO CUSTOMER(C_ID, C_LAST, C_ADDRESS)
      VALUES (CUSTOMER_SEQUENCE.NEXTVAL, P_C_LAST, P_C_ADDRESS);
      COMMIT;
    END ;
    
    PROCEDURE CUSTOMER_INSERT(P_C_LAST VARCHAR2, P_C_BIRTHDATE DATE) AS
    BEGIN
      INSERT INTO CUSTOMER(C_ID, C_LAST, C_BIRTHDATE)
      VALUES (CUSTOMER_SEQUENCE.NEXTVAL, P_C_LAST, P_C_BIRTHDATE);
      COMMIT;
    END ;
    
    PROCEDURE CUSTOMER_INSERT(P_C_LAST VARCHAR2, P_C_FIRST VARCHAR2, P_C_BIRTHDATE DATE) AS
    BEGIN
      INSERT INTO CUSTOMER(C_ID, C_LAST, C_FIRST, C_BIRTHDATE)
      VALUES (CUSTOMER_SEQUENCE.NEXTVAL, P_C_LAST, P_C_FIRST, P_C_BIRTHDATE);
      COMMIT;
    END ;
    
    PROCEDURE CUSTOMER_INSERT(P_C_ID NUMBER, P_C_LAST VARCHAR2, P_C_BIRTHDATE DATE) AS
    BEGIN
      INSERT INTO CUSTOMER(C_ID, C_LAST, C_BIRTHDATE)
      VALUES (P_C_ID, P_C_LAST, P_C_BIRTHDATE);
      COMMIT;
    END ;
END;
/

EXEC CUSTOMER_PACKAGE.CUSTOMER_INSERT('LaSalle', '2000 Saint-Catherine');
EXEC CUSTOMER_PACKAGE.CUSTOMER_INSERT('Jean', TO_DATE('2003-01-02', 'YYYY-MM-DD'));
EXEC CUSTOMER_PACKAGE.CUSTOMER_INSERT('Landeiro', 'Bruno', TO_DATE('1993-02-18', 'YYYY-MM-DD'));
EXEC CUSTOMER_PACKAGE.CUSTOMER_INSERT(90, 'Levesque', TO_DATE('1976-11-20', 'YYYY-MM-DD'));
delete from customer where c_id >= 7;
SPOOL OFF