SPOOL BRUNO_PROJECT_PART_7_Q3_Q4_SPOOL.txt
SELECT TO_CHAR(SYSDATE, 'DD Month Year Day HH:MI:SS Am') from dual;
SET SERVEROUTPUT ON;

-- Question 3:
-- Run script 7clearwater in schemas des02
-- Using CURSOR FOR LOOP syntax 2 in a procedure to display all items 
-- (item_id, item_desc, cat_id) under each item, display all the inventories 
-- belong to it
CREATE OR REPLACE PROCEDURE P7_Q3 AS
BEGIN 
  FOR OBJ_ITEM IN (SELECT ITEM_ID, ITEM_DESC, CAT_ID FROM ITEM) LOOP
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('---ITEM---');
    DBMS_OUTPUT.PUT_LINE(OBJ_ITEM.ITEM_ID ||', '|| OBJ_ITEM.ITEM_DESC ||', CAT_ID: '|| OBJ_ITEM.CAT_ID);
    DBMS_OUTPUT.PUT_LINE('---INVENTORY---');
    FOR OBJ_INV IN ( SELECT INV_ID, COLOR, INV_SIZE, INV_PRICE, INV_QOH FROM INVENTORY WHERE ITEM_ID = OBJ_ITEM.ITEM_ID) LOOP
      DBMS_OUTPUT.PUT_LINE(OBJ_INV.INV_ID||', COLOR: '|| OBJ_INV.COLOR ||', SIZE: '|| OBJ_INV.INV_SIZE 
        || ', PRICE $: '|| OBJ_INV.INV_PRICE||', QUANTITY: '|| OBJ_INV.INV_QOH);
    END LOOP;
  END LOOP;
END;
/
EXEC P7_Q3;
-- Question 4:
-- Modify question 3 to display beside the item description the value of the item (value = inv_price * inv_qoh).
CREATE OR REPLACE PROCEDURE P7_Q4 AS
BEGIN 
  FOR OBJ_ITEM IN (SELECT ITEM.ITEM_ID, ITEM.ITEM_DESC, ITEM.CAT_ID, SUM(INV_PRICE * INV_QOH) "VALUE"
    FROM ITEM JOIN INVENTORY ON INVENTORY.ITEM_ID = ITEM.ITEM_ID 
    GROUP BY ITEM.ITEM_ID, ITEM.ITEM_DESC, ITEM.CAT_ID) LOOP
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('---ITEM---');
    DBMS_OUTPUT.PUT_LINE(OBJ_ITEM.ITEM_ID ||', '|| OBJ_ITEM.ITEM_DESC || ', VALUE: $ '|| OBJ_ITEM.VALUE ||' , CAT_ID: '|| OBJ_ITEM.CAT_ID);
    DBMS_OUTPUT.PUT_LINE('---INVENTORY---');
    FOR OBJ_INV IN (SELECT INV_ID, COLOR, INV_SIZE, INV_PRICE, INV_QOH FROM INVENTORY WHERE ITEM_ID = OBJ_ITEM.ITEM_ID) LOOP
      DBMS_OUTPUT.PUT_LINE(OBJ_INV.INV_ID||', COLOR: '|| OBJ_INV.COLOR ||', SIZE: '|| OBJ_INV.INV_SIZE||', PRICE $: '|| OBJ_INV.INV_PRICE||', QUANTITY: '|| OBJ_INV.INV_QOH);
    END LOOP;
  END LOOP;
END;
/
EXEC P7_Q4;


SPOOL OFF;